/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AptosCoinInfo: Codable, Sendable {
	public let decimals: Int32
	public let name: String
	public let symbol: String

	public init(decimals: Int32, name: String, symbol: String) {
		self.decimals = decimals
		self.name = name
		self.symbol = symbol
	}
}

public struct AptosLedger: Codable, Sendable {
	public let chain_id: Int32
	public let ledger_version: String

	public init(chain_id: Int32, ledger_version: String) {
		self.chain_id = chain_id
		self.ledger_version = ledger_version
	}
}
