/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AptosResource<T: Codable & Sendable>: Codable, Sendable {
	public let type: String
	public let data: T

	public init(type: String, data: T) {
		self.type = type
		self.data = data
	}
}

public struct AptosResourceCoin: Codable, Sendable {
	public let value: String

	public init(value: String) {
		self.value = value
	}
}

public struct AptosResourceBalance: Codable, Sendable {
	public let coin: AptosResourceCoin

	public init(coin: AptosResourceCoin) {
		self.coin = coin
	}
}

public struct AptosResourceBalanceOptional: Codable, Sendable {
	public let coin: AptosResourceCoin?

	public init(coin: AptosResourceCoin?) {
		self.coin = coin
	}
}
