/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AptosAccount: Codable, Sendable {
	public let sequence_number: String

	public init(sequence_number: String) {
		self.sequence_number = sequence_number
	}
}
