/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct GraphqlRequest: Codable, Sendable {
	public let operationName: String
	public let variables: [String: String]
	public let query: String

	public init(operationName: String, variables: [String: String], query: String) {
		self.operationName = operationName
		self.variables = variables
		self.query = query
	}
}
