files:
  include:
  - "Gem/**/*.swift"
  - "App.swift"
  - "App-Configuration.swift"
  exclude:
  - "Gem/Resources/**/*.swift"
  - "Packages/**/Sources/**/*.swift"
  - "GemTests/**/*.swift"
elements:
  havingAccessLevel:
  - public
  - open
  showMembersWithAccessLevel:
  - public
  - package
  - internal
  - private
  showGenerics: true
  showNestedTypes: false
  showExtensions: merged
  showMemberAccessLevelAttribute: true
theme: plain
relationships:
  inheritance:
    label: "inherits from"
    exclude:
    - "Codable"
    - "Equatable"
    - "Identifiable"
    - "@retroactive Identifiable"
    - "Sendable"
    - "Hashable"
    - "View"
    - "@retroactive LocalizedError"
    - "Comparable"
  realize:
    label: "conforms to"
  dependency:
    label: "extends"
stereotypes:
  class:
    name: class
    spot:
      character: C
      color: AliceBlue
  struct:
    spot:
      character: S
      color: AntiqueWhite
  extension:
    spot:
      character: X
      color: AntiqueWhite
  enum:
    spot:
      character: E
      color: AntiqueWhite
  protocol:
    spot:
      character: P
      color: AntiqueWhite
texts:
  title: "Gem iOS"
  