/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct BitcoinBlockbook: Codable {
	public let inSync: Bool
	public let lastBlockTime: Bool

	public init(inSync: Bool, lastBlockTime: Bool) {
		self.inSync = inSync
		self.lastBlockTime = lastBlockTime
	}
}

public struct BitcoinNodeInfo: Codable {
	public let blockbook: BitcoinBlockbook

	public init(blockbook: BitcoinBlockbook) {
		self.blockbook = blockbook
	}
}
