/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct BitcoinBlock: Codable {
	public let previousBlockHash: String?

	public init(previousBlockHash: String?) {
		self.previousBlockHash = previousBlockHash
	}
}
