/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct BitcoinBlockbook: Codable {
	public let inSync: Bool
	public let lastBlockTime: String
	public let bestHeight: Int

	public init(inSync: Bool, lastBlockTime: String, bestHeight: Int) {
		self.inSync = inSync
		self.lastBlockTime = lastBlockTime
		self.bestHeight = bestHeight
	}
}

public struct BitcoinNodeInfo: Codable {
	public let blockbook: BitcoinBlockbook

	public init(blockbook: BitcoinBlockbook) {
		self.blockbook = blockbook
	}
}
