/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct ApprovalData: Codable, Equatable, Hashable, Sendable {
	public let token: String
	public let spender: String
	public let value: String

	public init(token: String, spender: String, value: String) {
		self.token = token
		self.spender = spender
		self.value = value
	}
}
