/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct SolanaValue<T: Codable & Sendable>: Codable, Sendable {
	public let value: T

	public init(value: T) {
		self.value = value
	}
}
