/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct SolanaPrioritizationFee: Codable {
	public let prioritizationFee: Int32

	public init(prioritizationFee: Int32) {
		self.prioritizationFee = prioritizationFee
	}
}
