/*
 Generated by typeshare 1.7.0
 */

import Foundation

public struct SolanaTransactionError: Codable {
	public init() {}
}

public struct SolanaTransactionMeta: Codable {
	public let err: SolanaTransactionError?

	public init(err: SolanaTransactionError?) {
		self.err = err
	}
}

public struct SolanaTransaction: Codable {
	public let meta: SolanaTransactionMeta
	public let slot: Int32

	public init(meta: SolanaTransactionMeta, slot: Int32) {
		self.meta = meta
		self.slot = slot
	}
}
