/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct SolanaBlockhash: Codable {
	public let blockhash: String

	public init(blockhash: String) {
		self.blockhash = blockhash
	}
}

public struct SolanaBlockhashResult: Codable {
	public let value: SolanaBlockhash

	public init(value: SolanaBlockhash) {
		self.value = value
	}
}
