/*
 Generated by typeshare 1.7.0
 */

import Foundation

public struct SolanaPrioritizationFee: Codable {
	public let prioritizationFee: Int32

	public init(prioritizationFee: Int32) {
		self.prioritizationFee = prioritizationFee
	}
}
