/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct SolanaAccountMeta: Codable, Sendable {
	public let pubkey: String
	public let isSigner: Bool
	public let isWritable: Bool

	public init(pubkey: String, isSigner: Bool, isWritable: Bool) {
		self.pubkey = pubkey
		self.isSigner = isSigner
		self.isWritable = isWritable
	}
}

public struct SolanaInstruction: Codable, Sendable {
	public let programId: String
	public let accounts: [SolanaAccountMeta]
	public let data: String

	public init(programId: String, accounts: [SolanaAccountMeta], data: String) {
		self.programId = programId
		self.accounts = accounts
		self.data = data
	}
}

public struct SolanaTransactionError: Codable, Sendable {
	public init() {}
}

public struct SolanaTransactionMeta: Codable, Sendable {
	public let err: SolanaTransactionError?

	public init(err: SolanaTransactionError?) {
		self.err = err
	}
}

public struct SolanaTransaction: Codable, Sendable {
	public let meta: SolanaTransactionMeta
	public let slot: Int32

	public init(meta: SolanaTransactionMeta, slot: Int32) {
		self.meta = meta
		self.slot = slot
	}
}
