/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct SolanaStakeAccountDataParsedInfoStakeDelegation: Codable {
	public let voter: String
	public let stake: String
	public let activationEpoch: String
	public let deactivationEpoch: String

	public init(voter: String, stake: String, activationEpoch: String, deactivationEpoch: String) {
		self.voter = voter
		self.stake = stake
		self.activationEpoch = activationEpoch
		self.deactivationEpoch = deactivationEpoch
	}
}

public struct SolanaStakeAccountDataParsedInfoStake: Codable {
	public let delegation: SolanaStakeAccountDataParsedInfoStakeDelegation

	public init(delegation: SolanaStakeAccountDataParsedInfoStakeDelegation) {
		self.delegation = delegation
	}
}

public struct SolanaStakeAccountDataParsedInfoMeta: Codable {
	public let rentExemptReserve: String

	public init(rentExemptReserve: String) {
		self.rentExemptReserve = rentExemptReserve
	}
}

public struct SolanaStakeAccountDataParsedInfo: Codable {
	public let stake: SolanaStakeAccountDataParsedInfoStake
	public let meta: SolanaStakeAccountDataParsedInfoMeta

	public init(stake: SolanaStakeAccountDataParsedInfoStake, meta: SolanaStakeAccountDataParsedInfoMeta) {
		self.stake = stake
		self.meta = meta
	}
}

public struct SolanaStakeAccountDataParsed: Codable {
	public let info: SolanaStakeAccountDataParsedInfo

	public init(info: SolanaStakeAccountDataParsedInfo) {
		self.info = info
	}
}

public struct SolanaStakeAccountData: Codable {
	public let parsed: SolanaStakeAccountDataParsed

	public init(parsed: SolanaStakeAccountDataParsed) {
		self.parsed = parsed
	}
}

public struct SolanaStakeAccount: Codable {
	public let lamports: Int
	public let space: Int32
	public let data: SolanaStakeAccountData

	public init(lamports: Int, space: Int32, data: SolanaStakeAccountData) {
		self.lamports = lamports
		self.space = space
		self.data = data
	}
}

public struct SolanaTokenAccount: Codable {
	public let pubkey: String

	public init(pubkey: String) {
		self.pubkey = pubkey
	}
}

public struct SolanaTokenAccountResult<T: Codable>: Codable {
	public let account: T
	public let pubkey: String

	public init(account: T, pubkey: String) {
		self.account = account
		self.pubkey = pubkey
	}
}
