/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct SolanaPrioritizationFee: Codable, Sendable {
	public let prioritizationFee: Int

	public init(prioritizationFee: Int) {
		self.prioritizationFee = prioritizationFee
	}
}
