/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct TronAccount: Codable, Sendable {
	public let balance: UInt64?
	public let address: String?

	public init(balance: UInt64?, address: String?) {
		self.balance = balance
		self.address = address
	}
}

public struct TronAccountRequest: Codable, Sendable {
	public let address: String
	public let visible: Bool

	public init(address: String, visible: Bool) {
		self.address = address
		self.visible = visible
	}
}

public struct TronAccountUsage: Codable, Sendable {
	public let freeNetUsed: Int32?
	public let freeNetLimit: Int32?

	public init(freeNetUsed: Int32?, freeNetLimit: Int32?) {
		self.freeNetUsed = freeNetUsed
		self.freeNetLimit = freeNetLimit
	}
}

public struct TronEmptyAccount: Codable, Sendable {
	public let address: String?

	public init(address: String?) {
		self.address = address
	}
}
