/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct Account: Codable, Equatable, Hashable, Sendable {
	public let chain: Chain
	public let address: String
	public let derivationPath: String
	public let extendedPublicKey: String?

	public init(chain: Chain, address: String, derivationPath: String, extendedPublicKey: String?) {
		self.chain = chain
		self.address = address
		self.derivationPath = derivationPath
		self.extendedPublicKey = extendedPublicKey
	}
}
