/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct Asset: Codable, Sendable {
	public let id: AssetId
	public let name: String
	public let symbol: String
	public let decimals: Int32
	public let type: AssetType

	public init(id: AssetId, name: String, symbol: String, decimals: Int32, type: AssetType) {
		self.id = id
		self.name = name
		self.symbol = symbol
		self.decimals = decimals
		self.type = type
	}
}
