/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct AssetMetaData: Codable, Equatable, Hashable, Sendable {
	public let isEnabled: Bool
	public let isBalanceEnabled: Bool
	public let isBuyEnabled: Bool
	public let isSellEnabled: Bool
	public let isSwapEnabled: Bool
	public let isStakeEnabled: Bool
	public let stakingApr: Double?
	public let isEarnEnabled: Bool
	public let earnApr: Double?
	public let isPinned: Bool
	public let isActive: Bool
	public let rankScore: Int32

	public init(isEnabled: Bool, isBalanceEnabled: Bool, isBuyEnabled: Bool, isSellEnabled: Bool, isSwapEnabled: Bool, isStakeEnabled: Bool, stakingApr: Double?, isEarnEnabled: Bool, earnApr: Double?, isPinned: Bool, isActive: Bool, rankScore: Int32) {
		self.isEnabled = isEnabled
		self.isBalanceEnabled = isBalanceEnabled
		self.isBuyEnabled = isBuyEnabled
		self.isSellEnabled = isSellEnabled
		self.isSwapEnabled = isSwapEnabled
		self.isStakeEnabled = isStakeEnabled
		self.stakingApr = stakingApr
		self.isEarnEnabled = isEarnEnabled
		self.earnApr = earnApr
		self.isPinned = isPinned
		self.isActive = isActive
		self.rankScore = rankScore
	}
}
