/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct AssetId: Codable, Equatable, Hashable, Sendable {
	public let chain: Chain
	public let tokenId: String?

	public init(chain: Chain, tokenId: String?) {
		self.chain = chain
		self.tokenId = tokenId
	}
}
