/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AssetPriceInfo: Codable, Sendable {
	public let assetId: String
	public let price: Price
	public let market: AssetMarket

	public init(assetId: String, price: Price, market: AssetMarket) {
		self.assetId = assetId
		self.price = price
		self.market = market
	}
}
