/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct BalanceMetadata: Codable, Equatable, Hashable, Sendable {
	public let votes: UInt32
	public let energyAvailable: UInt32
	public let energyTotal: UInt32
	public let bandwidthAvailable: UInt32
	public let bandwidthTotal: UInt32

	public init(votes: UInt32, energyAvailable: UInt32, energyTotal: UInt32, bandwidthAvailable: UInt32, bandwidthTotal: UInt32) {
		self.votes = votes
		self.energyAvailable = energyAvailable
		self.energyTotal = energyTotal
		self.bandwidthAvailable = bandwidthAvailable
		self.bandwidthTotal = bandwidthTotal
	}
}
