/*
 Generated by typeshare 1.9.2
 */

import Foundation

public enum BalanceType: String, Codable, CaseIterable, Equatable {
	case available
	case locked
	case frozen
	case staked
	case pending
	case rewards
	case reserved
}
