/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum BalanceType: String, Codable, CaseIterable, Equatable, Sendable {
	case available
	case locked
	case frozen
	case staked
	case pending
	case rewards
	case reserved
}
