/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct BlockExplorerLink: Codable, Equatable, Hashable {
	public let name: String
	public let link: String

	public init(name: String, link: String) {
		self.name = name
		self.link = link
	}
}
