/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct BroadcastOptions: Codable, Equatable, Hashable, Sendable {
	public let skipPreflight: Bool

	public init(skipPreflight: Bool) {
		self.skipPreflight = skipPreflight
	}
}
