/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum Chain: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case bitcoin
	case bitcoinCash = "bitcoincash"
	case litecoin
	case ethereum
	case smartChain = "smartchain"
	case solana
	case polygon
	case thorchain
	case cosmos
	case osmosis
	case arbitrum
	case ton
	case tron
	case doge
	case zcash
	case optimism
	case aptos
	case base
	case avalancheC = "avalanchec"
	case sui
	case xrp
	case opBNB = "opbnb"
	case fantom
	case gnosis
	case celestia
	case injective
	case sei
	case manta
	case blast
	case noble
	case zkSync = "zksync"
	case linea
	case mantle
	case celo
	case near
	case world
	case stellar
	case sonic
	case algorand
	case polkadot
	case plasma
	case cardano
	case abstract
	case berachain
	case ink
	case unichain
	case hyperliquid
	case hyperCore = "hypercore"
	case monad
	case xLayer = "xlayer"
	case stable
}
