/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum StakeChain: String, Codable, CaseIterable, Equatable, Sendable {
	case cosmos
	case osmosis
	case injective
	case sei
	case celestia
	case solana
	case sui
	case smartChain = "smartchain"
	case ethereum
}
