/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum StakeChain: String, Codable, CaseIterable, Equatable, Sendable {
	case cosmos
	case osmosis
	case injective
	case sei
	case celestia
	case ethereum
	case solana
	case sui
	case smartChain = "smartchain"
	case tron
	case aptos
	case hyperCore = "hypercore"
}
