/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum Chain: String, Codable, CaseIterable, Equatable, Sendable {
	case bitcoin
	case litecoin
	case ethereum
	case smartChain = "smartchain"
	case solana
	case polygon
	case thorchain
	case cosmos
	case osmosis
	case arbitrum
	case ton
	case tron
	case doge
	case optimism
	case aptos
	case base
	case avalancheC = "avalanchec"
	case sui
	case xrp
	case opBNB = "opbnb"
	case fantom
	case gnosis
	case celestia
	case injective
	case sei
	case manta
	case blast
	case noble
	case zkSync = "zksync"
	case linea
	case mantle
	case celo
	case near
}
