/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct ChainAddress: Codable, Equatable, Hashable, Sendable {
	public let chain: Chain
	public let address: String

	public init(chain: Chain, address: String) {
		self.chain = chain
		self.address = address
	}
}
