/*
 Generated by typeshare 1.9.2
 */

import Foundation

public enum EVMChain: String, Codable, CaseIterable, Equatable {
	case ethereum
	case smartChain = "smartchain"
	case polygon
	case arbitrum
	case optimism
	case base
	case avalancheC = "avalanchec"
	case opBNB = "opbnb"
	case fantom
	case gnosis
	case manta
	case blast
	case zkSync = "zksync"
	case linea
	case mantle
	case celo
}
