/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum CosmosChain: String, Codable, CaseIterable, Equatable, Sendable {
	case cosmos
	case osmosis
	case celestia
	case thorchain
	case injective
	case sei
	case noble
}

public enum CosmosDenom: String, Codable, CaseIterable, Equatable, Sendable {
	case rune
	case uatom
	case uosmo
	case utia
	case inj
	case usei
	case uusdc
}
