/*
 Generated by typeshare 1.9.2
 */

import Foundation

public enum ChainType: String, Codable, CaseIterable, Equatable, Hashable {
	case ethereum
	case bitcoin
	case solana
	case cosmos
	case ton
	case tron
	case aptos
	case sui
	case xrp
	case near
}
