/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum ChainType: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case ethereum
	case bitcoin
	case solana
	case cosmos
	case ton
	case tron
	case aptos
	case sui
	case xrp
	case near
}
