/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum BitcoinChain: String, Codable, CaseIterable, Equatable, Sendable {
	case bitcoin
	case bitcoinCash = "bitcoincash"
	case litecoin
	case doge
	case zcash
}
