/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum NFTChain: String, Codable, CaseIterable, Equatable, Sendable {
	case ethereum
	case polygon
	case solana
	case smartChain = "smartchain"
}
