/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum EVMChain: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case ethereum
	case smartChain = "smartchain"
	case polygon
	case plasma
	case arbitrum
	case optimism
	case base
	case avalancheC = "avalanchec"
	case opBNB = "opbnb"
	case fantom
	case gnosis
	case manta
	case blast
	case zkSync = "zksync"
	case linea
	case mantle
	case celo
	case world
	case sonic
	case abstract
	case berachain
	case ink
	case unichain
	case hyperliquid
	case monad
	case xLayer = "xlayer"
}
