/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct ChartCandleStick: Codable, Equatable, Sendable {
	public let date: Date
	public let open: Double
	public let high: Double
	public let low: Double
	public let close: Double
	public let volume: Double

	public init(date: Date, open: Double, high: Double, low: Double, close: Double, volume: Double) {
		self.date = date
		self.open = open
		self.high = high
		self.low = low
		self.close = close
		self.volume = volume
	}
}

public struct ChartDateValue: Codable, Equatable, Sendable {
	public let date: Date
	public let value: Double

	public init(date: Date, value: Double) {
		self.date = date
		self.value = value
	}
}
