/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Contact: Codable, Equatable, Hashable, Identifiable, Sendable {
	public let id: String
	public let name: String
	public let description: String?
	public let createdAt: Date
	public let updatedAt: Date

	public init(id: String, name: String, description: String?, createdAt: Date, updatedAt: Date) {
		self.id = id
		self.name = name
		self.description = description
		self.createdAt = createdAt
		self.updatedAt = updatedAt
	}
}

public struct ContactAddress: Codable, Equatable, Hashable, Identifiable, Sendable {
	public let id: String
	public let contactId: String
	public let address: String
	public let chain: Chain
	public let memo: String?

	public init(id: String, contactId: String, address: String, chain: Chain, memo: String?) {
		self.id = id
		self.contactId = contactId
		self.address = address
		self.chain = chain
		self.memo = memo
	}
}

public struct ContactData: Codable, Equatable, Hashable, Sendable {
	public let contact: Contact
	public let addresses: [ContactAddress]

	public init(contact: Contact, addresses: [ContactAddress]) {
		self.contact = contact
		self.addresses = addresses
	}
}
