/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Contact: Codable, Equatable, Hashable, Sendable {
	public let name: String
	public let address: String
	public let chain: Chain
	public let memo: String?
	public let description: String?

	public init(name: String, address: String, chain: Chain, memo: String?, description: String?) {
		self.name = name
		self.address = address
		self.chain = chain
		self.memo = memo
		self.description = description
	}
}
