/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Device: Codable, Equatable, Sendable {
	public let id: String
	public let platform: Platform
	public let platformStore: PlatformStore
	public let os: String
	public let model: String
	public let token: String
	public let locale: String
	public let version: String
	public let currency: String
	public let isPushEnabled: Bool
	public let isPriceAlertsEnabled: Bool?
	public let subscriptionsVersion: Int32

	public init(id: String, platform: Platform, platformStore: PlatformStore, os: String, model: String, token: String, locale: String, version: String, currency: String, isPushEnabled: Bool, isPriceAlertsEnabled: Bool?, subscriptionsVersion: Int32) {
		self.id = id
		self.platform = platform
		self.platformStore = platformStore
		self.os = os
		self.model = model
		self.token = token
		self.locale = locale
		self.version = version
		self.currency = currency
		self.isPushEnabled = isPushEnabled
		self.isPriceAlertsEnabled = isPriceAlertsEnabled
		self.subscriptionsVersion = subscriptionsVersion
	}
}

public struct MigrateDeviceIdRequest: Codable, Equatable, Sendable {
	public let oldDeviceId: String
	public let publicKey: String

	public init(oldDeviceId: String, publicKey: String) {
		self.oldDeviceId = oldDeviceId
		self.publicKey = publicKey
	}
}
