/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct DeviceToken: Codable, Equatable, Sendable {
	public let token: String
	public let expiresAt: UInt64

	public init(token: String, expiresAt: UInt64) {
		self.token = token
		self.expiresAt = expiresAt
	}
}
