/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct EarnTransaction: Codable, Sendable {
	public let chain: Chain
	public let from: String
	public let to: String
	public let data: String
	public let value: String?
	public let approval: ApprovalData?

	public init(chain: Chain, from: String, to: String, data: String, value: String?, approval: ApprovalData?) {
		self.chain = chain
		self.from = from
		self.to = to
		self.data = data
		self.value = value
		self.approval = approval
	}
}
