/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct EarnPosition: Codable, Equatable, Hashable, Sendable {
	public let base: EarnPositionBase
	public let provider: EarnProvider
	public let price: Price?

	public init(base: EarnPositionBase, provider: EarnProvider, price: Price?) {
		self.base = base
		self.provider = provider
		self.price = price
	}
}
