/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum EarnPositionState: String, Codable, CaseIterable, Equatable, Sendable {
	case active
	case pending
	case inactive
	case activating
	case deactivating
	case awaitingWithdrawal = "awaitingwithdrawal"
}

public struct EarnPositionBase: Codable, Equatable, Hashable, Sendable {
	public let assetId: AssetId
	public let state: EarnPositionState
	public let balance: String
	public let shares: String
	public let rewards: String
	public let unlockDate: Date?
	public let positionId: String
	public let providerId: String

	public init(assetId: AssetId, state: EarnPositionState, balance: String, shares: String, rewards: String, unlockDate: Date?, positionId: String, providerId: String) {
		self.assetId = assetId
		self.state = state
		self.balance = balance
		self.shares = shares
		self.rewards = rewards
		self.unlockDate = unlockDate
		self.positionId = positionId
		self.providerId = providerId
	}
}
