/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct PriorityFeeValue: Codable, Equatable, Sendable {
	public let priority: FeePriority
	public let value: String

	public init(priority: FeePriority, value: String) {
		self.priority = priority
		self.value = value
	}
}
