/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatRate: Codable, Sendable {
	public let symbol: String
	public let rate: Double

	public init(symbol: String, rate: Double) {
		self.symbol = symbol
		self.rate = rate
	}
}
