/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum FiatQuoteType: String, Codable, Equatable, Hashable, Sendable {
	case buy
	case sell
}

public enum FiatTransactionStatus: String, Codable, Equatable, Hashable, Sendable {
	case complete
	case pending
	case failed
	case unknown
}

public struct FiatTransaction: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let assetId: AssetId
	public let transactionType: FiatQuoteType
	public let provider: FiatProviderName
	public let status: FiatTransactionStatus
	public let fiatAmount: Double
	public let fiatCurrency: String
	public let value: String
	public let createdAt: Date

	public init(id: String, assetId: AssetId, transactionType: FiatQuoteType, provider: FiatProviderName, status: FiatTransactionStatus, fiatAmount: Double, fiatCurrency: String, value: String, createdAt: Date) {
		self.id = id
		self.assetId = assetId
		self.transactionType = transactionType
		self.provider = provider
		self.status = status
		self.fiatAmount = fiatAmount
		self.fiatCurrency = fiatCurrency
		self.value = value
		self.createdAt = createdAt
	}
}

public struct FiatTransactionInfo: Codable, Equatable, Hashable, Sendable {
	public let transaction: FiatTransaction
	public let asset: Asset
	public let detailsUrl: String?

	public init(transaction: FiatTransaction, asset: Asset, detailsUrl: String?) {
		self.transaction = transaction
		self.asset = asset
		self.detailsUrl = detailsUrl
	}
}
