/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum FiatQuoteType: String, Codable, Equatable, Hashable, Sendable {
	case buy
	case sell
}

public enum FiatTransactionStatus: String, Codable, Equatable, Hashable, Sendable {
	case complete
	case pending
	case failed
	case unknown
}

public struct FiatTransaction: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let assetId: AssetId
	public let transactionType: FiatQuoteType
	public let providerId: FiatProviderName
	public let providerTransactionId: String?
	public let status: FiatTransactionStatus
	public let fiatAmount: Double
	public let fiatCurrency: String
	public let value: String
	public let transactionHash: String?
	public let address: String?
	public let createdAt: Date
	public let updatedAt: Date

	public init(id: String, assetId: AssetId, transactionType: FiatQuoteType, providerId: FiatProviderName, providerTransactionId: String?, status: FiatTransactionStatus, fiatAmount: Double, fiatCurrency: String, value: String, transactionHash: String?, address: String?, createdAt: Date, updatedAt: Date) {
		self.id = id
		self.assetId = assetId
		self.transactionType = transactionType
		self.providerId = providerId
		self.providerTransactionId = providerTransactionId
		self.status = status
		self.fiatAmount = fiatAmount
		self.fiatCurrency = fiatCurrency
		self.value = value
		self.transactionHash = transactionHash
		self.address = address
		self.createdAt = createdAt
		self.updatedAt = updatedAt
	}
}

public struct FiatTransactionInfo: Codable, Equatable, Hashable, Sendable {
	public let transaction: FiatTransaction
	public let asset: Asset
	public let detailsUrl: String?

	public init(transaction: FiatTransaction, asset: Asset, detailsUrl: String?) {
		self.transaction = transaction
		self.asset = asset
		self.detailsUrl = detailsUrl
	}
}
