/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatAssets: Codable, Sendable {
	public let version: UInt32
	public let assetIds: [String]

	public init(version: UInt32, assetIds: [String]) {
		self.version = version
		self.assetIds = assetIds
	}
}
