/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct FiatProvider: Codable, Equatable {
	public let name: String
	public let imageUrl: String

	public init(name: String, imageUrl: String) {
		self.name = name
		self.imageUrl = imageUrl
	}
}
