/*
 Generated by typeshare 1.12.0
 */

import Foundation

public struct FiatQuoteRequest: Codable, Sendable {
	public let assetId: String
	public let fiatCurrency: String
	public let fiatAmount: Double
	public let cryptoAmount: Double?
	public let walletAddress: String

	public init(assetId: String, fiatCurrency: String, fiatAmount: Double, cryptoAmount: Double?, walletAddress: String) {
		self.assetId = assetId
		self.fiatCurrency = fiatCurrency
		self.fiatAmount = fiatAmount
		self.cryptoAmount = cryptoAmount
		self.walletAddress = walletAddress
	}
}
