/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct FiatQuoteRequest: Codable, Sendable {
	public let amount: Double
	public let currency: String

	public init(amount: Double, currency: String) {
		self.amount = amount
		self.currency = currency
	}
}
