/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum GrowthProviderType: String, Codable, CaseIterable, Equatable, Sendable {
	case stake
	case earn
}

public enum YieldProvider: String, Codable, CaseIterable, Equatable, Sendable {
	case yo
}
