/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum LatencyType: String, Codable, Equatable, Hashable, Sendable {
	case fast
	case normal
	case slow
}

public struct Latency: Codable, Equatable, Hashable, Sendable {
	public let latency_type: LatencyType
	public let value: Double

	public init(latency_type: LatencyType, value: Double) {
		self.latency_type = latency_type
		self.value = value
	}
}
