/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum LinkType: String, Codable, Equatable, Hashable, Sendable {
	case x
	case discord
	case reddit
	case telegram
	case gitHub = "github"
	case youTube = "youtube"
	case facebook
	case website
	case coingecko
	case openSea = "opensea"
	case instagram
	case magicEden = "magiceden"
	case coinMarketCap = "coinmarketcap"
	case tikTok = "tiktok"
}
