/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum CoreListItemIcon: Codable, Equatable, Sendable {
	case emoji(CoreEmoji)
	case asset(AssetId)
	case image(String)

	enum CodingKeys: String, CodingKey, Codable {
		case emoji,
			asset,
			image
	}

	private enum ContainerCodingKeys: String, CodingKey {
		case type, value
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: ContainerCodingKeys.self)
		if let type = try? container.decode(CodingKeys.self, forKey: .type) {
			switch type {
			case .emoji:
				if let content = try? container.decode(CoreEmoji.self, forKey: .value) {
					self = .emoji(content)
					return
				}
			case .asset:
				if let content = try? container.decode(AssetId.self, forKey: .value) {
					self = .asset(content)
					return
				}
			case .image:
				if let content = try? container.decode(String.self, forKey: .value) {
					self = .image(content)
					return
				}
			}
		}
		throw DecodingError.typeMismatch(CoreListItemIcon.self, DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Wrong type for CoreListItemIcon"))
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: ContainerCodingKeys.self)
		switch self {
		case .emoji(let content):
			try container.encode(CodingKeys.emoji, forKey: .type)
			try container.encode(content, forKey: .value)
		case .asset(let content):
			try container.encode(CodingKeys.asset, forKey: .type)
			try container.encode(content, forKey: .value)
		case .image(let content):
			try container.encode(CodingKeys.image, forKey: .type)
			try container.encode(content, forKey: .value)
		}
	}
}

public enum CoreListItemBadge: String, Codable, Equatable, Sendable {
	case new
}

public struct CoreListItem: Codable, Equatable, Sendable {
	public let id: String
	public let title: String
	public let subtitle: String?
	public let value: String?
	public let subvalue: String?
	public let icon: CoreListItemIcon?
	public let badge: CoreListItemBadge?
	public let url: String?

	public init(id: String, title: String, subtitle: String?, value: String?, subvalue: String?, icon: CoreListItemIcon?, badge: CoreListItemBadge?, url: String?) {
		self.id = id
		self.title = title
		self.subtitle = subtitle
		self.value = value
		self.subvalue = subvalue
		self.icon = icon
		self.badge = badge
		self.url = url
	}
}

public enum CoreEmoji: String, Codable, Equatable, Sendable {
	case gift
	case gem
	case party
	case warning
}
