/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct NameRecord: Codable, Hashable, Sendable {
	public let name: String
	public let chain: Chain
	public let address: String
	public let provider: String

	public init(name: String, chain: Chain, address: String, provider: String) {
		self.name = name
		self.chain = chain
		self.address = address
		self.provider = provider
	}
}

public enum NameProvider: String, Codable, Sendable {
	case ud
	case ens
	case sns
	case ton
	case tree
	case spaceid
	case eths
	case did
	case suins
	case aptos
	case injective
	case icns
	case lens
	case basenames
	case hyperliquid
	case allDomains = "alldomains"
}
