/*
 Generated by typeshare 1.12.0
 */

import Foundation

public enum NFTType: String, Codable, Sendable {
	case erc721
	case erc1155
	case spl
}

public struct NFTImage: Codable, Sendable {
	public let imageUrl: String
	public let previewImageUrl: String
	public let originalSourceUrl: String

	public init(imageUrl: String, previewImageUrl: String, originalSourceUrl: String) {
		self.imageUrl = imageUrl
		self.previewImageUrl = previewImageUrl
		self.originalSourceUrl = originalSourceUrl
	}
}

public struct NFTAttribute: Codable, Sendable {
	public let name: String
	public let value: String

	public init(name: String, value: String) {
		self.name = name
		self.value = value
	}
}

public struct NFTAsset: Codable, Sendable {
	public let id: String
	public let collectionId: String
	public let tokenId: String
	public let tokenType: NFTType
	public let name: String
	public let description: String?
	public let chain: Chain
	public let image: NFTImage
	public let attributes: [NFTAttribute]

	public init(id: String, collectionId: String, tokenId: String, tokenType: NFTType, name: String, description: String?, chain: Chain, image: NFTImage, attributes: [NFTAttribute]) {
		self.id = id
		self.collectionId = collectionId
		self.tokenId = tokenId
		self.tokenType = tokenType
		self.name = name
		self.description = description
		self.chain = chain
		self.image = image
		self.attributes = attributes
	}
}

public struct NFTCollection: Codable, Sendable {
	public let id: String
	public let name: String
	public let description: String?
	public let chain: Chain
	public let contractAddress: String
	public let image: NFTImage
	public let isVerified: Bool

	public init(id: String, name: String, description: String?, chain: Chain, contractAddress: String, image: NFTImage, isVerified: Bool) {
		self.id = id
		self.name = name
		self.description = description
		self.chain = chain
		self.contractAddress = contractAddress
		self.image = image
		self.isVerified = isVerified
	}
}

public struct NFTData: Codable, Sendable {
	public let collection: NFTCollection
	public let assets: [NFTAsset]

	public init(collection: NFTCollection, assets: [NFTAsset]) {
		self.collection = collection
		self.assets = assets
	}
}
