/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Notification: Codable, Equatable, Sendable {
	public let wallet_id: String
	public let notification_type: NotificationType
	public let is_read: Bool
	public let metadata: AnyCodableValue?
	public let created_at: Date

	public init(wallet_id: String, notification_type: NotificationType, is_read: Bool, metadata: AnyCodableValue?, created_at: Date) {
		self.wallet_id = wallet_id
		self.notification_type = notification_type
		self.is_read = is_read
		self.metadata = metadata
		self.created_at = created_at
	}
}
