/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Notification: Codable, Equatable, Sendable {
	public let walletId: String
	public let notificationType: NotificationType
	public let isRead: Bool
	public let metadata: AnyCodableValue?
	public let readAt: Date?
	public let createdAt: Date

	public init(walletId: String, notificationType: NotificationType, isRead: Bool, metadata: AnyCodableValue?, readAt: Date?, createdAt: Date) {
		self.walletId = walletId
		self.notificationType = notificationType
		self.isRead = isRead
		self.metadata = metadata
		self.readAt = readAt
		self.createdAt = createdAt
	}
}

public struct NotificationRewardsMetadata: Codable, Equatable, Sendable {
	public let username: String
	public let points: Int32?

	public init(username: String, points: Int32?) {
		self.username = username
		self.points = points
	}
}
