/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct Notification: Codable, Equatable, Sendable {
	public let walletId: String
	public let readAt: Date?
	public let createdAt: Date
	public let asset: Asset?
	public let item: CoreListItem

	public init(walletId: String, readAt: Date?, createdAt: Date, asset: Asset?, item: CoreListItem) {
		self.walletId = walletId
		self.readAt = readAt
		self.createdAt = createdAt
		self.asset = asset
		self.item = item
	}
}
