/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum NotificationType: String, Codable, Equatable, Sendable {
	case referralJoined
	case rewardsEnabled
	case rewardsCodeDisabled
	case rewardsRedeemed
	case rewardsCreateUsername
	case rewardsInvite
}
