/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum PaymentType: String, Codable, Equatable, Hashable, Sendable {
	case card
	case googlePay = "google_pay"
	case applePay = "apple_pay"
}
