/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum PerpetualMarginType: String, Codable, Equatable, Hashable, Sendable {
	case cross
	case isolated
}

public struct PriceTarget: Codable, Equatable, Hashable, Sendable {
	public let price: Double?
	public let percentage: Double?

	public init(price: Double?, percentage: Double?) {
		self.price = price
		self.percentage = percentage
	}
}

public struct PerpetualPosition: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let perpetualId: String
	public let size: Double
	public let sizeValue: Double
	public let leverage: UInt8
	public let entryPrice: Double?
	public let liquidationPrice: Double?
	public let marginType: PerpetualMarginType
	public let direction: PerpetualDirection
	public let marginAmount: Double
	public let takeProfit: PriceTarget?
	public let stopLoss: PriceTarget?
	public let pnl: Double
	public let funding: Float?

	public init(id: String, perpetualId: String, size: Double, sizeValue: Double, leverage: UInt8, entryPrice: Double?, liquidationPrice: Double?, marginType: PerpetualMarginType, direction: PerpetualDirection, marginAmount: Double, takeProfit: PriceTarget?, stopLoss: PriceTarget?, pnl: Double, funding: Float?) {
		self.id = id
		self.perpetualId = perpetualId
		self.size = size
		self.sizeValue = sizeValue
		self.leverage = leverage
		self.entryPrice = entryPrice
		self.liquidationPrice = liquidationPrice
		self.marginType = marginType
		self.direction = direction
		self.marginAmount = marginAmount
		self.takeProfit = takeProfit
		self.stopLoss = stopLoss
		self.pnl = pnl
		self.funding = funding
	}
}
