/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum Platform: String, Codable, Equatable, Sendable {
	case ios
	case android
}

public enum PlatformStore: String, Codable, CaseIterable, Equatable, Sendable {
	case appStore
	case googlePlay
	case fdroid
	case huawei
	case solanaStore
	case samsungStore
	case apkUniversal
}
