/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum Platform: String, Codable, Equatable {
	case ios
	case android
}

public enum PlatformStore: String, Codable, CaseIterable, Equatable {
	case appStore = "app_store"
	case googlePlay = "google_play"
	case fdroid
	case huawei
	case solanaStore = "solana_store"
	case samsungStore = "samsung_store"
	case apkUniversal = "apk_universal"
}
