/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum PlatformStore: String, Codable, CaseIterable, Equatable, Sendable {
	case appStore
	case googlePlay
	case fdroid
	case huawei
	case solanaStore
	case samsungStore
	case apkUniversal
	case emerald
	case local
}
