/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct PerpetualPortfolioDataPoint: Codable, Equatable, Hashable, Sendable {
	public let date: Date
	public let value: Double

	public init(date: Date, value: Double) {
		self.date = date
		self.value = value
	}
}

public struct PerpetualPortfolioTimeframeData: Codable, Equatable, Hashable, Sendable {
	public let accountValueHistory: [PerpetualPortfolioDataPoint]
	public let pnlHistory: [PerpetualPortfolioDataPoint]
	public let volume: Double

	public init(accountValueHistory: [PerpetualPortfolioDataPoint], pnlHistory: [PerpetualPortfolioDataPoint], volume: Double) {
		self.accountValueHistory = accountValueHistory
		self.pnlHistory = pnlHistory
		self.volume = volume
	}
}

public struct PerpetualPortfolio: Codable, Equatable, Hashable, Sendable {
	public let day: PerpetualPortfolioTimeframeData?
	public let week: PerpetualPortfolioTimeframeData?
	public let month: PerpetualPortfolioTimeframeData?
	public let allTime: PerpetualPortfolioTimeframeData?

	public init(day: PerpetualPortfolioTimeframeData?, week: PerpetualPortfolioTimeframeData?, month: PerpetualPortfolioTimeframeData?, allTime: PerpetualPortfolioTimeframeData?) {
		self.day = day
		self.week = week
		self.month = month
		self.allTime = allTime
	}
}
