/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct PerpetualAccountSummary: Codable, Equatable, Hashable, Sendable {
	public let accountValue: Double
	public let accountLeverage: Double
	public let marginUsage: Double
	public let unrealizedPnl: Double

	public init(accountValue: Double, accountLeverage: Double, marginUsage: Double, unrealizedPnl: Double) {
		self.accountValue = accountValue
		self.accountLeverage = accountLeverage
		self.marginUsage = marginUsage
		self.unrealizedPnl = unrealizedPnl
	}
}

public struct PerpetualPortfolioTimeframeData: Codable, Equatable, Hashable, Sendable {
	public let accountValueHistory: [ChartDateValue]
	public let pnlHistory: [ChartDateValue]
	public let volume: Double

	public init(accountValueHistory: [ChartDateValue], pnlHistory: [ChartDateValue], volume: Double) {
		self.accountValueHistory = accountValueHistory
		self.pnlHistory = pnlHistory
		self.volume = volume
	}
}

public struct PerpetualPortfolio: Codable, Equatable, Hashable, Sendable {
	public let day: PerpetualPortfolioTimeframeData?
	public let week: PerpetualPortfolioTimeframeData?
	public let month: PerpetualPortfolioTimeframeData?
	public let allTime: PerpetualPortfolioTimeframeData?
	public let accountSummary: PerpetualAccountSummary?

	public init(day: PerpetualPortfolioTimeframeData?, week: PerpetualPortfolioTimeframeData?, month: PerpetualPortfolioTimeframeData?, allTime: PerpetualPortfolioTimeframeData?, accountSummary: PerpetualAccountSummary?) {
		self.day = day
		self.week = week
		self.month = month
		self.allTime = allTime
		self.accountSummary = accountSummary
	}
}

public enum PerpetualPortfolioChartType: String, Codable, CaseIterable, Equatable, Identifiable, Sendable {
	case value
	case pnl
}
