/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct Price: Codable, Equatable, Hashable, Sendable {
	public let price: Double
	public let priceChangePercentage24h: Double
	public let updatedAt: Date

	public init(price: Double, priceChangePercentage24h: Double, updatedAt: Date) {
		self.price = price
		self.priceChangePercentage24h = priceChangePercentage24h
		self.updatedAt = updatedAt
	}
}

public struct PriceData: Codable, Equatable, Sendable {
	public let asset: Asset
	public let price: Price?
	public let priceAlerts: [PriceAlert]
	public let market: AssetMarket?
	public let links: [AssetLink]

	public init(asset: Asset, price: Price?, priceAlerts: [PriceAlert], market: AssetMarket?, links: [AssetLink]) {
		self.asset = asset
		self.price = price
		self.priceAlerts = priceAlerts
		self.market = market
		self.links = links
	}
}
