/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct PriceAlert: Codable, Equatable, Hashable {
	public let assetId: String
	public let price: Double?
	public let pricePercentChange: Double?

	public init(assetId: String, price: Double?, pricePercentChange: Double?) {
		self.assetId = assetId
		self.price = price
		self.pricePercentChange = pricePercentChange
	}
}

public struct PriceAlertData: Codable, Equatable, Hashable {
	public let asset: Asset
	public let price: Price?
	public let priceAlert: PriceAlert

	public init(asset: Asset, price: Price?, priceAlert: PriceAlert) {
		self.asset = asset
		self.price = price
		self.priceAlert = priceAlert
	}
}
