/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct Price: Codable, Equatable, Hashable, Sendable {
	public let price: Double
	public let priceChangePercentage24h: Double

	public init(price: Double, priceChangePercentage24h: Double) {
		self.price = price
		self.priceChangePercentage24h = priceChangePercentage24h
	}
}

public struct PriceData: Codable, Sendable {
	public let asset: Asset
	public let price: Price?
	public let priceAlert: PriceAlert?
	public let details: AssetDetailsInfo?

	public init(asset: Asset, price: Price?, priceAlert: PriceAlert?, details: AssetDetailsInfo?) {
		self.asset = asset
		self.price = price
		self.priceAlert = priceAlert
		self.details = details
	}
}
