/*
 Generated by typeshare 1.7.0
 */

import Foundation

public struct Price: Codable, Equatable, Hashable {
	public let price: Double
	public let priceChangePercentage24h: Double

	public init(price: Double, priceChangePercentage24h: Double) {
		self.price = price
		self.priceChangePercentage24h = priceChangePercentage24h
	}
}
