/*
 Generated by typeshare 1.7.0
 */

import Foundation

public enum PushNotificationTypes: String, Codable, Equatable {
	case transaction
}

public struct PushNotification: Codable, Equatable {
	public let type: PushNotificationTypes
	public let data: Transaction

	public init(type: PushNotificationTypes, data: Transaction) {
		self.type = type
		self.data = data
	}
}
