/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum PushNotificationTypes: String, Codable, Equatable {
	case test
	case transaction
	case priceAlert = "price_alert"
}

public struct PushNotificationPayloadType: Codable, Equatable {
	public let type: PushNotificationTypes

	public init(type: PushNotificationTypes) {
		self.type = type
	}
}

public struct PushNotificationTransaction: Codable, Equatable {
	public let wallet_index: Int32
	public let transaction: Transaction

	public init(wallet_index: Int32, transaction: Transaction) {
		self.wallet_index = wallet_index
		self.transaction = transaction
	}
}
