/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum RecentActivityType: String, Codable, CaseIterable, Equatable, Sendable {
	case search
	case transfer
	case receive
	case fiatBuy
	case fiatSell
}
