/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct Recipient: Codable, Equatable, Hashable, Sendable {
	public let name: String?
	public let address: String
	public let memo: String?

	public init(name: String?, address: String, memo: String?) {
		self.name = name
		self.address = address
		self.memo = memo
	}
}

public struct RecipientData: Codable, Equatable, Hashable, Sendable {
	public let asset: Asset
	public let recipient: Recipient
	public let amount: String?

	public init(asset: Asset, recipient: Recipient, amount: String?) {
		self.asset = asset
		self.recipient = recipient
		self.amount = amount
	}
}
