/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct ResponseError: Codable, Sendable {
	public let error: String

	public init(error: String) {
		self.error = error
	}
}

public struct ResponseResult<T: Codable & Sendable>: Codable, Sendable {
	public let data: T
	public let error: ResponseError?

	public init(data: T, error: ResponseError?) {
		self.data = data
		self.error = error
	}
}
