/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct RedemptionRequest: Codable, Sendable {
	public let id: String

	public init(id: String) {
		self.id = id
	}
}

public enum RewardRedemptionType: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case asset
	case giftAsset
}

public struct RewardRedemptionOption: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let redemptionType: RewardRedemptionType
	public let points: Int32
	public let asset: Asset?
	public let value: String
	public let remaining: Int32?

	public init(id: String, redemptionType: RewardRedemptionType, points: Int32, asset: Asset?, value: String, remaining: Int32?) {
		self.id = id
		self.redemptionType = redemptionType
		self.points = points
		self.asset = asset
		self.value = value
		self.remaining = remaining
	}
}

public enum RedemptionStatus: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case pending
	case completed
	case failed
}

public struct RewardRedemption: Codable, Equatable, Hashable, Sendable {
	public let id: Int32
	public let option: RewardRedemptionOption
	public let status: RedemptionStatus
	public let transactionId: String?
	public let createdAt: Date

	public init(id: Int32, option: RewardRedemptionOption, status: RedemptionStatus, transactionId: String?, createdAt: Date) {
		self.id = id
		self.option = option
		self.status = status
		self.transactionId = transactionId
		self.createdAt = createdAt
	}
}

public struct RedemptionResult: Codable, Sendable {
	public let redemption: RewardRedemption

	public init(redemption: RewardRedemption) {
		self.redemption = redemption
	}
}

public struct ReferralActivation: Codable, Equatable, Hashable, Sendable {
	public let verifyCompleted: Bool
	public let verifyAfter: Date?
	public let swapCompleted: Bool
	public let swapAmount: Int32

	public init(verifyCompleted: Bool, verifyAfter: Date?, swapCompleted: Bool, swapAmount: Int32) {
		self.verifyCompleted = verifyCompleted
		self.verifyAfter = verifyAfter
		self.swapCompleted = swapCompleted
		self.swapAmount = swapAmount
	}
}

public struct ReferralQuota: Codable, Equatable, Hashable, Sendable {
	public let limit: Int32
	public let available: Int32

	public init(limit: Int32, available: Int32) {
		self.limit = limit
		self.available = available
	}
}

public struct ReferralAllowance: Codable, Equatable, Hashable, Sendable {
	public let daily: ReferralQuota
	public let weekly: ReferralQuota

	public init(daily: ReferralQuota, weekly: ReferralQuota) {
		self.daily = daily
		self.weekly = weekly
	}
}

public struct ReferralCode: Codable, Sendable {
	public let code: String

	public init(code: String) {
		self.code = code
	}
}

public struct ReferralCodeActivation: Codable, Equatable, Hashable, Sendable {
	public let swapCompleted: Bool
	public let swapAmount: Int32

	public init(swapCompleted: Bool, swapAmount: Int32) {
		self.swapCompleted = swapCompleted
		self.swapAmount = swapAmount
	}
}

public struct ReferralLeader: Codable, Equatable, Hashable, Sendable {
	public let username: String
	public let referrals: Int32
	public let points: Int32

	public init(username: String, referrals: Int32, points: Int32) {
		self.username = username
		self.referrals = referrals
		self.points = points
	}
}

public struct ReferralLeaderboard: Codable, Equatable, Hashable, Sendable {
	public let daily: [ReferralLeader]
	public let weekly: [ReferralLeader]
	public let monthly: [ReferralLeader]

	public init(daily: [ReferralLeader], weekly: [ReferralLeader], monthly: [ReferralLeader]) {
		self.daily = daily
		self.weekly = weekly
		self.monthly = monthly
	}
}

public enum RewardEventType: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case createUsername
	case invitePending
	case inviteNew
	case inviteExisting
	case joined
	case disabled
}

public struct RewardEvent: Codable, Equatable, Hashable, Sendable {
	public let event: RewardEventType
	public let points: Int32
	public let createdAt: Date

	public init(event: RewardEventType, points: Int32, createdAt: Date) {
		self.event = event
		self.points = points
		self.createdAt = createdAt
	}
}

public enum RewardStatus: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case unverified
	case pending
	case verified
	case trusted
	case disabled
}

public struct Rewards: Codable, Equatable, Hashable, Sendable {
	public let code: String?
	public let referralCount: Int32
	public let points: Int32
	public let usedReferralCode: String?
	public let status: RewardStatus
	public let redemptionOptions: [RewardRedemptionOption]
	public let disableReason: String?
	public let referralAllowance: ReferralAllowance
	public let referralCodeActivation: ReferralCodeActivation?
	public let referralActivation: ReferralActivation?

	public init(code: String?, referralCount: Int32, points: Int32, usedReferralCode: String?, status: RewardStatus, redemptionOptions: [RewardRedemptionOption], disableReason: String?, referralAllowance: ReferralAllowance, referralCodeActivation: ReferralCodeActivation?, referralActivation: ReferralActivation?) {
		self.code = code
		self.referralCount = referralCount
		self.points = points
		self.usedReferralCode = usedReferralCode
		self.status = status
		self.redemptionOptions = redemptionOptions
		self.disableReason = disableReason
		self.referralAllowance = referralAllowance
		self.referralCodeActivation = referralCodeActivation
		self.referralActivation = referralActivation
	}
}
