/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct ReferralCode: Codable, Sendable {
	public let code: String

	public init(code: String) {
		self.code = code
	}
}

public struct Rewards: Codable, Equatable, Hashable, Sendable {
	public let code: String?
	public let referralCount: Int32
	public let points: Int32
	public let usedReferralCode: String?

	public init(code: String?, referralCount: Int32, points: Int32, usedReferralCode: String?) {
		self.code = code
		self.referralCount = referralCount
		self.points = points
		self.usedReferralCode = usedReferralCode
	}
}

public enum RewardsEvent: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case createUsername
	case invite
	case joined
}

public struct RewardsEventItem: Codable, Equatable, Hashable, Sendable {
	public let event: RewardsEvent
	public let points: Int32
	public let createdAt: Date

	public init(event: RewardsEvent, points: Int32, createdAt: Date) {
		self.event = event
		self.points = points
		self.createdAt = createdAt
	}
}
