/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct ScanAddress: Codable, Equatable, Sendable {
	public let name: String?
	public let address: String
	public let isVerified: Bool
	public let isFraudulent: Bool
	public let isMemoRequired: Bool

	public init(name: String?, address: String, isVerified: Bool, isFraudulent: Bool, isMemoRequired: Bool) {
		self.name = name
		self.address = address
		self.isVerified = isVerified
		self.isFraudulent = isFraudulent
		self.isMemoRequired = isMemoRequired
	}
}
