/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct SearchResponse: Codable, Sendable {
	public let assets: [AssetBasic]
	public let perpetuals: [Perpetual]
	public let nfts: [NFTCollection]

	public init(assets: [AssetBasic], perpetuals: [Perpetual], nfts: [NFTCollection]) {
		self.assets = assets
		self.perpetuals = perpetuals
		self.nfts = nfts
	}
}

public enum SearchItemType: String, Codable, Sendable {
	case asset
	case perpetual
	case nft
}
