/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct SecurityMetadata: Codable, Equatable, Sendable {
	public let name: String
	public let verified: Bool
	public let requiredMemo: Bool

	public init(name: String, verified: Bool, requiredMemo: Bool) {
		self.name = name
		self.verified = verified
		self.requiredMemo = requiredMemo
	}
}

public struct SecurityResponse: Codable, Equatable, Sendable {
	public let malicious: Bool
	public let reason: String
	public let provider: String
	public let metadata: SecurityMetadata?

	public init(malicious: Bool, reason: String, provider: String, metadata: SecurityMetadata?) {
		self.malicious = malicious
		self.reason = reason
		self.provider = provider
		self.metadata = metadata
	}
}
