/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct SupportDevice: Codable, Equatable, Sendable {
	public let supportDeviceId: String
	public let unread: Int32

	public init(supportDeviceId: String, unread: Int32) {
		self.supportDeviceId = supportDeviceId
		self.unread = unread
	}
}
