/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct NewSupportDevice: Codable, Equatable, Sendable {
	public let supportDeviceId: String
	public let deviceId: String

	public init(supportDeviceId: String, deviceId: String) {
		self.supportDeviceId = supportDeviceId
		self.deviceId = deviceId
	}
}

public struct SupportDevice: Codable, Equatable, Sendable {
	public let supportDeviceId: String
	public let unread: Int32

	public init(supportDeviceId: String, unread: Int32) {
		self.supportDeviceId = supportDeviceId
		self.unread = unread
	}
}
