/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum SwapProvider: String, Codable, Equatable, Hashable, Sendable {
	case uniswapV3 = "uniswap_v3"
	case uniswapV4 = "uniswap_v4"
	case pancakeswapV3 = "pancakeswap_v3"
	case aerodrome
	case pancakeswapAptosV2 = "pancakeswap_aptos_v2"
	case thorchain
	case jupiter
	case across
	case oku
	case wagmi
	case cetus
	case stonfiV2 = "stonfi_v2"
	case mayan
	case reservoir
	case symbiosis
	case chainflip
	case cetusAggregator = "cetus_aggregator"
	case relay
	case hyperliquid
}
