/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum SwapProvider: String, Codable, Equatable, Sendable {
	case uniswapV3 = "uniswapv3"
	case uniswapV4 = "uniswapv4"
	case pancakeSwapV3 = "pancakeswapv3"
	case pancakeSwapAptosV2 = "pancakeswapaptosv2"
	case thorchain
	case orca
	case jupiter
	case across
	case oku
	case wagmi
	case cetus
	case stonFiV2 = "stonfiv2"
	case mayan
	case reservoir
}

public enum SwapProviderMode: String, Codable, Equatable, Sendable {
	case onChain = "onchain"
	case crossChain = "crosschain"
	case bridge
}
