/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum AssetTag: String, Codable, Equatable, Hashable, Sendable {
	case trending
	case trendingFiatPurchase = "trending_fiat_purchase"
	case gainers
	case losers
	case new
	case stablecoins
}
