/*
 Generated by typeshare 1.12.0
 */

import Foundation

public enum AssetTag: String, Codable, Equatable, Hashable, Sendable {
	case trending
	case trendingFiat = "trending_fiat"
	case gainers
	case losers
	case new
	case stablecoins
}
