/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum TransactionState: String, Codable, CaseIterable, Equatable, Sendable {
	case pending
	case confirmed
	case inTransit
	case failed
	case reverted
}
