/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum TransactionDirection: String, Codable, CaseIterable, Equatable, Sendable {
	case selfTransfer = "self"
	case outgoing
	case incoming
}
