/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct TransactionUtxoInput: Codable, Equatable, Sendable {
	public let address: String
	public let value: String

	public init(address: String, value: String) {
		self.address = address
		self.value = value
	}
}
