/*
 Generated by typeshare 1.9.2
 */

import Foundation

public enum TransactionType: String, Codable, CaseIterable, Equatable {
	case transfer
	case swap
	case tokenApproval
	case stakeDelegate
	case stakeUndelegate
	case stakeRewards
	case stakeRedelegate
	case stakeWithdraw
}
