/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct TransactionSwapMetadata: Codable, Sendable {
	public let fromAsset: AssetId
	public let fromValue: String
	public let toAsset: AssetId
	public let toValue: String

	public init(fromAsset: AssetId, fromValue: String, toAsset: AssetId, toValue: String) {
		self.fromAsset = fromAsset
		self.fromValue = fromValue
		self.toAsset = toAsset
		self.toValue = toValue
	}
}
