/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum TransferDataOutputAction: String, Codable, Equatable, Hashable, Sendable {
	case sign
	case send
}

public enum TransferDataOutputType: String, Codable, Equatable, Hashable, Sendable {
	case encodedTransaction
	case signature
}
