/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct TransactionWallet: Codable, Equatable, Sendable {
	public let transaction: Transaction
	public let wallet: Wallet

	public init(transaction: Transaction, wallet: Wallet) {
		self.transaction = transaction
		self.wallet = wallet
	}
}
