/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct TransactionExtended: Codable, Sendable {
	public let transaction: Transaction
	public let asset: Asset
	public let feeAsset: Asset
	public let price: Price?
	public let feePrice: Price?
	public let assets: [Asset]

	public init(transaction: Transaction, asset: Asset, feeAsset: Asset, price: Price?, feePrice: Price?, assets: [Asset]) {
		self.transaction = transaction
		self.asset = asset
		self.feeAsset = feeAsset
		self.price = price
		self.feePrice = feePrice
		self.assets = assets
	}
}
