/*
 Generated by typeshare 1.11.0
 */

import Foundation

public enum TransactionState: String, Codable, CaseIterable, Equatable, Sendable {
	case pending
	case confirmed
	case failed
	case reverted
}
