/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct StakeValidator: Codable, Equatable, Hashable {
	public let id: String
	public let name: String

	public init(id: String, name: String) {
		self.id = id
		self.name = name
	}
}
