/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum WalletConnectEthereumMethods: String, Codable, CaseIterable, Sendable {
	case chainId
	case sign
	case personalSign
	case signTypedData
	case signTypedDataV4
	case signTransaction
	case sendTransaction
	case sendRawTransaction
	case switchChain
	case addChain
}

public enum WalletConnectSolanaMethods: String, Codable, CaseIterable, Sendable {
	case signMessage
	case signTransaction
	case signAndSendTransaction
	case signAllTransactions
}

public enum WalletConnectSuiMethods: String, Codable, CaseIterable, Sendable {
	case signPersonalMessage
	case signTransaction
	case signAndExecuteTransaction
}
