/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct WalletConnectionSessionAppMetadata: Codable, Equatable, Hashable, Sendable {
	public let name: String
	public let description: String
	public let url: String
	public let icon: String

	public init(name: String, description: String, url: String, icon: String) {
		self.name = name
		self.description = description
		self.url = url
		self.icon = icon
	}
}

public struct WalletConnectionSessionProposal: Codable, Equatable, Hashable, Sendable {
	public let defaultWallet: Wallet
	public let wallets: [Wallet]
	public let metadata: WalletConnectionSessionAppMetadata

	public init(defaultWallet: Wallet, wallets: [Wallet], metadata: WalletConnectionSessionAppMetadata) {
		self.defaultWallet = defaultWallet
		self.wallets = wallets
		self.metadata = metadata
	}
}

public enum WalletConnectionVerificationStatus: String, Codable, Hashable, Sendable {
	case verified
	case unknown
	case invalid
	case malicious
}

public struct WCPairingProposal: Codable, Sendable {
	public let pairingId: String
	public let proposal: WalletConnectionSessionProposal
	public let verificationStatus: WalletConnectionVerificationStatus

	public init(pairingId: String, proposal: WalletConnectionSessionProposal, verificationStatus: WalletConnectionVerificationStatus) {
		self.pairingId = pairingId
		self.proposal = proposal
		self.verificationStatus = verificationStatus
	}
}

public enum WalletConnectionState: String, Codable, Hashable, Sendable {
	case started
	case active
	case expired
}

public struct WalletConnectionSession: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let sessionId: String
	public let state: WalletConnectionState
	public let chains: [Chain]
	public let createdAt: Date
	public let expireAt: Date
	public let metadata: WalletConnectionSessionAppMetadata

	public init(id: String, sessionId: String, state: WalletConnectionState, chains: [Chain], createdAt: Date, expireAt: Date, metadata: WalletConnectionSessionAppMetadata) {
		self.id = id
		self.sessionId = sessionId
		self.state = state
		self.chains = chains
		self.createdAt = createdAt
		self.expireAt = expireAt
		self.metadata = metadata
	}
}

public struct WalletConnection: Codable, Equatable, Hashable, Sendable {
	public let session: WalletConnectionSession
	public let wallet: Wallet

	public init(session: WalletConnectionSession, wallet: Wallet) {
		self.session = session
		self.wallet = wallet
	}
}

public enum WalletConnectionEvents: String, Codable, CaseIterable, Sendable {
	case connect
	case disconnect
	case accountsChanged
	case chainChanged
}

public enum WalletConnectionMethods: String, Codable, CaseIterable, Sendable {
	case ethChainId = "eth_chainId"
	case personalSign = "personal_sign"
	case ethSignTypedData = "eth_signTypedData"
	case ethSignTypedDataV4 = "eth_signTypedData_v4"
	case ethSignTransaction = "eth_signTransaction"
	case ethSendTransaction = "eth_sendTransaction"
	case ethSendRawTransaction = "eth_sendRawTransaction"
	case walletSwitchEthereumChain = "wallet_switchEthereumChain"
	case walletAddEthereumChain = "wallet_addEthereumChain"
	case solanaSignMessage = "solana_signMessage"
	case solanaSignTransaction = "solana_signTransaction"
	case solanaSignAndSendTransaction = "solana_signAndSendTransaction"
	case solanaSignAllTransactions = "solana_signAllTransactions"
	case suiSignPersonalMessage = "sui_signPersonalMessage"
	case suiSignTransaction = "sui_signTransaction"
	case suiSignAndExecuteTransaction = "sui_signAndExecuteTransaction"
}
