/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct WCBitcoinTransfer: Codable, Equatable, Hashable, Sendable {
	public let account: String
	public let recipientAddress: String
	public let amount: String
	public let memo: String?

	public init(account: String, recipientAddress: String, amount: String, memo: String?) {
		self.account = account
		self.recipientAddress = recipientAddress
		self.amount = amount
		self.memo = memo
	}
}

public struct WCEthereumTransaction: Codable, Equatable, Hashable, Sendable {
	public let chainId: String?
	public let from: String
	public let to: String
	public let value: String?
	public let gas: String?
	public let gasLimit: String?
	public let gasPrice: String?
	public let maxFeePerGas: String?
	public let maxPriorityFeePerGas: String?
	public let nonce: String?
	public let data: String?

	public init(chainId: String?, from: String, to: String, value: String?, gas: String?, gasLimit: String?, gasPrice: String?, maxFeePerGas: String?, maxPriorityFeePerGas: String?, nonce: String?, data: String?) {
		self.chainId = chainId
		self.from = from
		self.to = to
		self.value = value
		self.gas = gas
		self.gasLimit = gasLimit
		self.gasPrice = gasPrice
		self.maxFeePerGas = maxFeePerGas
		self.maxPriorityFeePerGas = maxPriorityFeePerGas
		self.nonce = nonce
		self.data = data
	}
}

public struct WCTonMessage: Codable, Equatable, Hashable, Sendable {
	public let address: String
	public let amount: String
	public let payload: String?
	public let stateInit: String?

	public init(address: String, amount: String, payload: String?, stateInit: String?) {
		self.address = address
		self.amount = amount
		self.payload = payload
		self.stateInit = stateInit
	}
}
