/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum WalletSource: String, Codable, Equatable, Hashable, Sendable {
	case create
	case `import`
}

public struct Wallet: Codable, Equatable, Hashable, Sendable {
	public let id: String
	public let name: String
	public let index: Int32
	public let type: WalletType
	public let accounts: [Account]
	public let order: Int32
	public let isPinned: Bool
	public let imageUrl: String?
	public let source: WalletSource

	public init(id: String, name: String, index: Int32, type: WalletType, accounts: [Account], order: Int32, isPinned: Bool, imageUrl: String?, source: WalletSource) {
		self.id = id
		self.name = name
		self.index = index
		self.type = type
		self.accounts = accounts
		self.order = order
		self.isPinned = isPinned
		self.imageUrl = imageUrl
		self.source = source
	}
}
