/*
 Generated by typeshare 1.9.2
 */

import Foundation

public enum WalletType: String, Codable, Equatable, Hashable {
	case multicoin
	case single
	case view
}

public struct Wallet: Codable, Equatable {
	public let id: String
	public let name: String
	public let index: Int32
	public let type: WalletType
	public let accounts: [Account]

	public init(id: String, name: String, index: Int32, type: WalletType, accounts: [Account]) {
		self.id = id
		self.name = name
		self.index = index
		self.type = type
		self.accounts = accounts
	}
}
