/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum WalletConnectBlockchainEthereumMethods: String, Codable, CaseIterable, Sendable {
	case chainId
	case sign
	case personalSign
	case signTypedData
	case signTypedDataV4
	case signTransaction
	case sendTransaction
	case sendRawTransaction
	case switchChain
	case addChain
}

public enum WalletConnectBlockchainSolanaMethods: String, Codable, CaseIterable, Sendable {
	case signMessage
	case signTransaction
	case signAndSendTransaction
	case signAllTransactions
}
