/*
 Generated by typeshare 1.13.3
 */

import Foundation

public enum WebSocketPriceActionType: String, Codable, Sendable {
	case subscribe
	case add
}

public struct WebSocketPriceAction: Codable, Sendable {
	public let action: WebSocketPriceActionType
	public let assets: [AssetId]?

	public init(action: WebSocketPriceActionType, assets: [AssetId]?) {
		self.action = action
		self.assets = assets
	}
}

public struct WebSocketPricePayload: Codable, Sendable {
	public let prices: [AssetPrice]
	public let rates: [FiatRate]

	public init(prices: [AssetPrice], rates: [FiatRate]) {
		self.prices = prices
		self.rates = rates
	}
}
