/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct WebSocketPricePayload: Codable, Sendable {
	public let prices: [AssetPrice]
	public let rates: [FiatRate]

	public init(prices: [AssetPrice], rates: [FiatRate]) {
		self.prices = prices
		self.rates = rates
	}
}
