/*
 Generated by typeshare 1.13.3
 */

import Foundation

public struct YieldData: Codable, Equatable, Hashable, Sendable {
	public let providerName: String
	public let contractAddress: String
	public let callData: String
	public let approval: ApprovalData?
	public let gasLimit: String?

	public init(providerName: String, contractAddress: String, callData: String, approval: ApprovalData?, gasLimit: String?) {
		self.providerName = providerName
		self.contractAddress = contractAddress
		self.callData = callData
		self.approval = approval
		self.gasLimit = gasLimit
	}
}

public enum YieldAction: String, Codable, Equatable, Hashable, Sendable {
	case deposit = "Deposit"
	case withdraw = "Withdraw"
}
