/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct TonTransactionId: Codable {
	public let hash: String

	public init(hash: String) {
		self.hash = hash
	}
}

public struct TonTransaction: Codable {
	public let transaction_id: TonTransactionId

	public init(transaction_id: TonTransactionId) {
		self.transaction_id = transaction_id
	}
}

public struct TonTransactionMessage: Codable {
	public let hash: String

	public init(hash: String) {
		self.hash = hash
	}
}

public struct TonJettonTokenContentData: Codable {
	public let name: String
	public let symbol: String
	public let decimals: String

	public init(name: String, symbol: String, decimals: String) {
		self.name = name
		self.symbol = symbol
		self.decimals = decimals
	}
}

public struct TonJettonTokenContent: Codable {
	public let type: String
	public let data: TonJettonTokenContentData

	public init(type: String, data: TonJettonTokenContentData) {
		self.type = type
		self.data = data
	}
}

public struct TonJettonToken: Codable {
	public let jetton_content: TonJettonTokenContent

	public init(jetton_content: TonJettonTokenContent) {
		self.jetton_content = jetton_content
	}
}

public struct TonJettonBalance: Codable {
	public let balance: UInt64

	public init(balance: UInt64) {
		self.balance = balance
	}
}
