/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct NearBlockHeader: Codable, Sendable {
	public let hash: String
	public let height: UInt64

	public init(hash: String, height: UInt64) {
		self.hash = hash
		self.height = height
	}
}

public struct NearBlock: Codable, Sendable {
	public let header: NearBlockHeader

	public init(header: NearBlockHeader) {
		self.header = header
	}
}

public struct NearGenesisConfig: Codable, Sendable {
	public let chain_id: String

	public init(chain_id: String) {
		self.chain_id = chain_id
	}
}
