/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct NearError: Codable, Sendable {
	public let message: String
	public let data: String?

	public init(message: String, data: String?) {
		self.message = message
		self.data = data
	}
}

public struct NearRPCError: Codable, Sendable {
	public let error: NearError

	public init(error: NearError) {
		self.error = error
	}
}
