/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct NearGasPrice: Codable, Sendable {
	public let gas_price: String

	public init(gas_price: String) {
		self.gas_price = gas_price
	}
}
