/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct NearAccount: Codable, Sendable {
	public let amount: String

	public init(amount: String) {
		self.amount = amount
	}
}

public struct NearAccountAccessKey: Codable, Sendable {
	public let nonce: Int

	public init(nonce: Int) {
		self.nonce = nonce
	}
}
