/*
 Generated by typeshare 1.9.2
 */

import Foundation

public struct CosmosHeader: Codable {
	public let chain_id: String

	public init(chain_id: String) {
		self.chain_id = chain_id
	}
}

public struct CosmosBlock: Codable {
	public let header: CosmosHeader

	public init(header: CosmosHeader) {
		self.header = header
	}
}

public struct CosmosBlockResponse: Codable {
	public let block: CosmosBlock

	public init(block: CosmosBlock) {
		self.block = block
	}
}
