/*
 Generated by typeshare 1.11.0
 */

import Foundation

public struct CosmosHeader: Codable {
	public let chain_id: String
	public let height: String

	public init(chain_id: String, height: String) {
		self.chain_id = chain_id
		self.height = height
	}
}

public struct CosmosBlock: Codable {
	public let header: CosmosHeader

	public init(header: CosmosHeader) {
		self.header = header
	}
}

public struct CosmosBlockResponse: Codable {
	public let block: CosmosBlock

	public init(block: CosmosBlock) {
		self.block = block
	}
}

public struct CosmosNodeInfo: Codable {
	public let network: String

	public init(network: String) {
		self.network = network
	}
}

public struct CosmosNodeInfoResponse: Codable {
	public let default_node_info: CosmosNodeInfo

	public init(default_node_info: CosmosNodeInfo) {
		self.default_node_info = default_node_info
	}
}
