/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AlgorandAccountAsset: Codable, Sendable {
	public let amount: UInt64
	public let asset_id: Int32

	enum CodingKeys: String, CodingKey, Codable {
		case amount,
			asset_id = "asset-id"
	}

	public init(amount: UInt64, asset_id: Int32) {
		self.amount = amount
		self.asset_id = asset_id
	}
}

public struct AlgorandAccount: Codable, Sendable {
	public let amount: UInt64
	public let assets: [AlgorandAccountAsset]
	public let min_balance: UInt64

	enum CodingKeys: String, CodingKey, Codable {
		case amount,
			assets,
			min_balance = "min-balance"
	}

	public init(amount: UInt64, assets: [AlgorandAccountAsset], min_balance: UInt64) {
		self.amount = amount
		self.assets = assets
		self.min_balance = min_balance
	}
}
