/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct AlgorandAsset: Codable, Sendable {
	public let decimals: Int32
	public let name: String
	public let unit_name: String

	enum CodingKeys: String, CodingKey, Codable {
		case decimals,
			name,
			unit_name = "unit-name"
	}

	public init(decimals: Int32, name: String, unit_name: String) {
		self.decimals = decimals
		self.name = name
		self.unit_name = unit_name
	}
}

public struct AlgorandAssetResponse: Codable, Sendable {
	public let params: AlgorandAsset

	public init(params: AlgorandAsset) {
		self.params = params
	}
}
