/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct XRPLatestBlock: Codable, Sendable {
	public let ledger_current_index: UInt64

	public init(ledger_current_index: UInt64) {
		self.ledger_current_index = ledger_current_index
	}
}
