/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct XRPDrops: Codable, Sendable {
	public let minimum_fee: String
	public let median_fee: String

	public init(minimum_fee: String, median_fee: String) {
		self.minimum_fee = minimum_fee
		self.median_fee = median_fee
	}
}

public struct XRPFee: Codable, Sendable {
	public let drops: XRPDrops

	public init(drops: XRPDrops) {
		self.drops = drops
	}
}
