/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct XRPResult<T: Codable & Sendable>: Codable, Sendable {
	public let result: T

	public init(result: T) {
		self.result = result
	}
}
