/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct XRPTransaction: Codable, Sendable {
	public let hash: String

	public init(hash: String) {
		self.hash = hash
	}
}

public struct XRPTransactionBroadcast: Codable, Sendable {
	public let accepted: Bool?
	public let engine_result_message: String?
	public let error_exception: String?
	public let tx_json: XRPTransaction?

	public init(accepted: Bool?, engine_result_message: String?, error_exception: String?, tx_json: XRPTransaction?) {
		self.accepted = accepted
		self.engine_result_message = engine_result_message
		self.error_exception = error_exception
		self.tx_json = tx_json
	}
}

public struct XRPTransactionStatus: Codable, Sendable {
	public let status: String

	public init(status: String) {
		self.status = status
	}
}
