/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct PolkadotEstimateFee: Codable, Sendable {
	public let partialFee: String

	public init(partialFee: String) {
		self.partialFee = partialFee
	}
}
