/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct PolkadotAccountBalance: Codable, Sendable {
	public let free: String
	public let reserved: String
	public let nonce: String

	public init(free: String, reserved: String, nonce: String) {
		self.free = free
		self.reserved = reserved
		self.nonce = nonce
	}
}
