/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct HypercoreCandlestick: Codable, Sendable {
	public let t: UInt64
	public let o: String
	public let h: String
	public let l: String
	public let c: String
	public let v: String

	public init(t: UInt64, o: String, h: String, l: String, c: String, v: String) {
		self.t = t
		self.o = o
		self.h = h
		self.l = l
		self.c = c
		self.v = v
	}
}
