/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct HypercoreErrorResponse: Codable, Sendable {
	public let response: String

	public init(response: String) {
		self.response = response
	}
}

public struct HypercoreResponse: Codable, Sendable {
	public let status: String

	public init(status: String) {
		self.status = status
	}
}
