/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct HypercoreAssetMetadata: Codable, Sendable {
	public let funding: String
	public let openInterest: String
	public let prevDayPx: String
	public let dayNtlVlm: String
	public let premium: String?
	public let oraclePx: String
	public let markPx: String
	public let midPx: String?
	public let impactPxs: [String]?
	public let dayBaseVlm: String

	public init(funding: String, openInterest: String, prevDayPx: String, dayNtlVlm: String, premium: String?, oraclePx: String, markPx: String, midPx: String?, impactPxs: [String]?, dayBaseVlm: String) {
		self.funding = funding
		self.openInterest = openInterest
		self.prevDayPx = prevDayPx
		self.dayNtlVlm = dayNtlVlm
		self.premium = premium
		self.oraclePx = oraclePx
		self.markPx = markPx
		self.midPx = midPx
		self.impactPxs = impactPxs
		self.dayBaseVlm = dayBaseVlm
	}
}
