/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct HypercoreReferredBy: Codable, Equatable, Sendable {
	public let code: String

	public init(code: String) {
		self.code = code
	}
}

public struct HypercoreReferral: Codable, Equatable, Sendable {
	public let referredBy: HypercoreReferredBy?
	public let cumVlm: String

	public init(referredBy: HypercoreReferredBy?, cumVlm: String) {
		self.referredBy = referredBy
		self.cumVlm = cumVlm
	}
}
