/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct SuiCoin: Codable, Sendable {
	public let coinType: String
	public let coinObjectId: String
	public let balance: String
	public let version: String
	public let digest: String

	public init(coinType: String, coinObjectId: String, balance: String, version: String, digest: String) {
		self.coinType = coinType
		self.coinObjectId = coinObjectId
		self.balance = balance
		self.version = version
		self.digest = digest
	}
}

