/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct SuiCoin: Codable, Sendable {
	public let coinType: String
	public let coinObjectId: String
	public let balance: String
	public let version: String
	public let digest: String

	public init(coinType: String, coinObjectId: String, balance: String, version: String, digest: String) {
		self.coinType = coinType
		self.coinObjectId = coinObjectId
		self.balance = balance
		self.version = version
		self.digest = digest
	}
}

public struct SuiCoinBalance: Codable, Sendable {
	public let coinType: String
	public let totalBalance: String

	public init(coinType: String, totalBalance: String) {
		self.coinType = coinType
		self.totalBalance = totalBalance
	}
}

public struct SuiCoinMetadata: Codable, Sendable {
	public let decimals: Int32
	public let name: String
	public let symbol: String

	public init(decimals: Int32, name: String, symbol: String) {
		self.decimals = decimals
		self.name = name
		self.symbol = symbol
	}
}
