/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct StellarTransactionBroadcast: Codable, Sendable {
	public let hash: String?
	public let title: String?

	public init(hash: String?, title: String?) {
		self.hash = hash
		self.title = title
	}
}

public struct StellarTransactionStatus: Codable, Sendable {
	public let successful: Bool
	public let fee_charged: String

	public init(successful: Bool, fee_charged: String) {
		self.successful = successful
		self.fee_charged = fee_charged
	}
}
