/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct StellarFeeCharged: Codable, Sendable {
	public let min: String
	public let p95: String

	public init(min: String, p95: String) {
		self.min = min
		self.p95 = p95
	}
}

public struct StellarFees: Codable, Sendable {
	public let last_ledger_base_fee: String
	public let fee_charged: StellarFeeCharged

	public init(last_ledger_base_fee: String, fee_charged: StellarFeeCharged) {
		self.last_ledger_base_fee = last_ledger_base_fee
		self.fee_charged = fee_charged
	}
}
