/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct StellarBalance: Codable, Sendable {
	public let balance: String
	public let asset_type: String
	public let asset_code: String?
	public let asset_issuer: String?

	public init(balance: String, asset_type: String, asset_code: String?, asset_issuer: String?) {
		self.balance = balance
		self.asset_type = asset_type
		self.asset_code = asset_code
		self.asset_issuer = asset_issuer
	}
}

public struct StellarAccount: Codable, Sendable {
	public let sequence: String
	public let balances: [StellarBalance]

	public init(sequence: String, balances: [StellarBalance]) {
		self.sequence = sequence
		self.balances = balances
	}
}
