/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct StellarNodeStatus: Codable, Sendable {
	public let ingest_latest_ledger: Int32
	public let network_passphrase: String

	public init(ingest_latest_ledger: Int32, network_passphrase: String) {
		self.ingest_latest_ledger = ingest_latest_ledger
		self.network_passphrase = network_passphrase
	}
}
