/*
 Generated by typeshare 1.13.2
 */

import Foundation

public struct CardanoSubmitTransactionHash: Codable, Sendable {
	public let hash: String

	public init(hash: String) {
		self.hash = hash
	}
}

public struct CardanoTransaction: Codable, Sendable {
	public let fee: String
	public let block: CardanoBlock

	public init(fee: String, block: CardanoBlock) {
		self.fee = fee
		self.block = block
	}
}

public struct CardanoTransactionBroadcast: Codable, Sendable {
	public let submitTransaction: CardanoSubmitTransactionHash?

	public init(submitTransaction: CardanoSubmitTransactionHash?) {
		self.submitTransaction = submitTransaction
	}
}

public struct CardanoTransactions: Codable, Sendable {
	public let transactions: [CardanoTransaction]

	public init(transactions: [CardanoTransaction]) {
		self.transactions = transactions
	}
}
