/*
 Generated by typeshare 1.13.2
 */

import Foundation

public enum EthereumBlockParameter: String, Codable, CaseIterable, Equatable, Hashable, Sendable {
	case latest
	case earliest
	case pending
	case finalized
	case safe
}
